export class AssetRegisterModel {
    printedStatus!:string;
    imageId!:string;
    siteName!:string;
    buildingName!:string;
    roomName!:string;
    warrantyCost!:number;
    productCode!: string;
    productName!: string;
    receiptId!: string;
    productId!: number;
    assetRegisterId!: number;
    assetActive!: boolean;
    depreciationRequired!: boolean;
    serialNo!: string;
    supplierId!: number;
    supplierName!: string;
    productDescription!: string;
    assetId!: number;
    manufacturePartNo!: string;
    purchasePrice!: number;
    categoryId!: number;
    subCategoryId!: number;
    brandId!: number;
    modelId!: number;
    assetStatusId!: number;
    assetConditionId!: number;
    departmentID!: number;
    departmentName!: string;
    employeeId!: number;
    employeeName!: string;
    locationId!: number;
    assetCategoryCode!: string;
    assetCategoryName!: string;
    assetSubCategoryCode!: string;
    assetSubCategoryName!: string;
    locationName!: string;
    brandName!: string;
    modelName!: string;
    warrantyStartDate!: Date;
    createdDate!:Date;
    warrantyEndDate!: Date;
    insuranceName!: string;
    insuranceEndDate!: Date;
    purchaseDate!: Date;
    insuranceValue!: number;
    insuranceStartDate!: Date;
    depreciationStartDate!: Date;
    depreciationPeriod!: string;
    depreciationStartValue!: string;
    depreciationPercentage!: number;
    disposed!: boolean;
    disposalMethodId!: number;
    disposalAmount!: number;
    disposalComment!: string;
    disposalDate!: Date;
    disposalEstAmount!: number;
    isMaintenanceRequired!: boolean;
    maintenanceStartDate!: Date;
    addDescription!: string;
    addQuantity!: number;
    addDateBought!: Date;
    isDeleted!: boolean;
    salvageValue!: number;
    depreciationValue!: number;
    accumulatedDepreciation!: number;
    bookValue!: number;
    addAmount!: number;
    warrantyAmount!: number;
    assetStatusName!:string;
    assetConditionName!:string;
    assetOwner!:string;
    extrlTagNumber!:string;
    manufactureSerialNo!:string;
    ownerID!:number;
    refDocumentType!:string;
    refDocumentNo!:string;
    refDocumentDate!:Date;
    units!:number;
}